services:
  site:
    network_mode: "host"
    container_name: docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:4b383ce285ed2556aa05a01c76305405a3fecd410af56e2d47a039c59bdc2f04
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
