services:
  site:
    network_mode: "host"
    container_name: docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:92a8086f817cfaf95bfca41d2f72382ae64e87389fe865f9b2f06335edb34073
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
