services:
  site:
    network_mode: "host"
    container_name: docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:4e87fa2c1aa4a31edfa4092cc50428e86bf129e5bb528e2b3bbc8661e2038339
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
