name: Update Images Page

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-images.yml'
      - 'scripts/update-images.sh'

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch image data and update page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/update-images.sh
          ./scripts/update-images.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          title: 'chore: update images page'
          branch: update-images
          branch-suffix: timestamp
          commit-message: 'chore: update images page'
          body: |
            This automated PR updates the images page with the latest container image data.
            
            - Updated stable images
            - Updated stable-daily images
            - Updated GTS images
            - Updated LTS images
          delete-branch: true
